// ─────────────────────────────────────────────
// STATIONS DATA
// ─────────────────────────────────────────────
const stations = [
  {id:"sa",  name:"إذاعة القرآن - السعودية",   name_en:"Quran Radio - Saudi Arabia",   url:"https://live.kwikmotion.com/sbrksaquranradiolive/ksaquranradio/chunks.m3u8",    cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"mk",  name:"نداء الإسلام - مكة",          name_en:"Nidaa Al Islam - Makkah",      url:"https://live.kwikmotion.com/sbrksanedaradiolive/ksanedaradio/chunks.m3u8",     cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"qa",  name:"إذاعة القرآن - قطر",           name_en:"Quran Radio - Qatar",          url:"https://live.kwikmotion.com/qmcquranradio2live/quranradio2/chunks.m3u8",       cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"doha",name:"إذاعة القرآن - الدوحة",       name_en:"Quran Radio - Doha",           url:"https://live.kwikmotion.com/qmcquranradiolive/quranradio/chunks.m3u8",         cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"bh",  name:"إذاعة القرآن - البحرين",      name_en:"Quran Radio - Bahrain",        url:"https://5c7b683162943.streamlock.net/live/ngrp:radio-106-1_all/chunklist_w1919732249_b981072.m3u8",cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"kw",  name:"إذاعة القرآن - الكويت",       name_en:"Quran Radio - Kuwait",         url:"https://kwtkrdota.cdn.mangomolo.com/qrrdo/qrrdo.stream_aac/chunklist.m3u8",    cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"kw2", name:"الذكر الحكيم - الكويت",        name_en:"Al-Dhikr Al-Hakim",            url:"https://kwtkrdota.cdn.mangomolo.com/daraerdo/daraerdo.stream_aac/chunklist.m3u8",cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"ae_shj",name:"إذاعة القرآن - الشارقة",   name_en:"Quran Radio - Sharjah",        url:"https://l3.itworkscdn.net/smcquranlive/quranradiolive/icecast.audio",          cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"ae_db", name:"إذاعة دبي للقرآن",           name_en:"Dubai Quran Radio",            url:"https://uk5.internet-radio.com/proxy/dubaiholyquran?mp=/stream;",              cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"ae_uq", name:"إذاعة القرآن - أم القيوين", name_en:"Umm Al Quwain Quran",          url:"http://ca.rcast.net:8058/;",                                                  cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"om",  name:"إذاعة القرآن - عمان",          name_en:"Quran Radio - Oman",           url:"https://partwota.cdn.mgmlcdn.com/quranrdoorg/quranrdo.stream_aac/chunklist.m3u8",cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"jo",  name:"إذاعة القرآن - الأردن",        name_en:"Quran Radio - Jordan",         url:"https://jrtv-live.ercdn.net/jrradio/quranradio.m3u8",                         cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"eg",  name:"إذاعة القرآن - القاهرة",       name_en:"Quran Radio - Cairo",          url:"https://stream.radiojar.com/8s5u5tpdtwzuv",                                  cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"dz",  name:"إذاعة القرآن - الجزائر",       name_en:"Quran Radio - Algeria",        url:"https://radiocoran.ice.infomaniak.ch/coran.mp3",                              cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"tn",  name:"إذاعة الزيتونة - تونس",        name_en:"Zitouna Radio - Tunisia",      url:"https://tv.radiotunisienne.tn/radiotn/zaitouna_video/chunklist_w754864815.m3u8",cat:"إذاعات الدول",cat_en:"State Radios"},
  {id:"ps",  name:"إذاعة القرآن - نابلس",         name_en:"Quran Radio - Nablus",         url:"https://quran-radio.org:8440/;?type=http&nocache=29",                         cat:"إذاعات الدول",cat_en:"State Radios"},

  {id:"156",name:"إذاعة الحرم المكي",             name_en:"Masjid Al Haram Radio",        url:"http://r7.tarat.com:8004/stream?type=http&nocache=114",                       cat:"منوعات",cat_en:"Others"},
  {id:"52", name:"تكبيرات العيد",                  name_en:"EID's TAKBEER",                url:"https://qurango.net/radio/eid",                                               cat:"منوعات",cat_en:"Others"},
  {id:"1",  name:"صور من حياة الصحابة",            name_en:"Sahaba Stories",               url:"https://qurango.net/radio/sahabah",                                           cat:"منوعات",cat_en:"Others"},
  {id:"2",  name:"تراتيل قصيرة متميزة",            name_en:"Amazing short Recitations",    url:"https://qurango.net/radio/tarateel",                                          cat:"منوعات",cat_en:"Others"},
  {id:"3",  name:"إذاعة آيات السكينة",             name_en:"Calm Recitations",             url:"https://qurango.net/radio/sakeenah",                                          cat:"منوعات",cat_en:"Others"},
  {id:"5",  name:"سورة البقرة - قراء مختلفون",    name_en:"Surah Al-Baqarah",             url:"https://qurango.net/radio/albaqarah",                                         cat:"منوعات",cat_en:"Others"},
  {id:"6",  name:"الإذاعة العامة - متنوعة",        name_en:"Main Radio",                   url:"https://qurango.net/radio/mix",                                               cat:"منوعات",cat_en:"Others"},
  {id:"7",  name:"تلاوات خاشعة",                   name_en:"Beautiful Recitations",        url:"https://qurango.net/radio/salma",                                             cat:"منوعات",cat_en:"Others"},
  {id:"105",name:"اختيارات فقهية بن باز",          name_en:"Fiqh Choices (Bin Baz)",       url:"https://qurango.net/radio/alaikhtiarat_alfiqhayh_bin_baz",                    cat:"منوعات",cat_en:"Others"},
  {id:"28", name:"الفتاوى العامة",                  name_en:"General Fatwas",               url:"https://qurango.net/radio/fatwa",                                             cat:"منوعات",cat_en:"Others"},
  {id:"17", name:"أذكار الصباح",                    name_en:"Morning Adhkar",               url:"https://qurango.net/radio/athkar_sabah",                                      cat:"منوعات",cat_en:"Others"},
  {id:"18", name:"أذكار المساء",                    name_en:"Evening Adhkar",               url:"https://qurango.net/radio/athkar_masa",                                       cat:"منوعات",cat_en:"Others"},
  {id:"24", name:"الرقية الشرعية",                  name_en:"Roqyah",                       url:"https://qurango.net/radio/roqiah",                                            cat:"منوعات",cat_en:"Others"},

  {id:"4",  name:"تفسير القرآن الكريم",            name_en:"Quran Tafseer",                url:"https://qurango.net/radio/tafseer",                                           cat:"تفسير",cat_en:"Tafseer"},
  {id:"31", name:"المختصر في التفسير",              name_en:"Brief Tafseer",                url:"https://qurango.net/radio/mukhtasartafsir",                                   cat:"تفسير",cat_en:"Tafseer"},
  {id:"30", name:"مختصر السيرة النبوية",           name_en:"Brief Prophet Bio",            url:"https://qurango.net/radio/almukhtasar_fi_alsiyra",                            cat:"السيرة النبوية",cat_en:"Prophet Bio"},
  {id:"104",name:"في ظلال السيرة",                  name_en:"Fi Zilal Al-Siyra",            url:"https://qurango.net/radio/fi_zilal_alsiyra",                                  cat:"السيرة النبوية",cat_en:"Prophet Bio"},

  {id:"8",  name:"أحمد الحواشي",      name_en:"Ahmad Al-Hawashi",            url:"https://qurango.net/radio/ahmad_alhawashi",                  cat:"قراء",cat_en:"Readers"},
  {id:"9",  name:"أحمد الطرالسي",     name_en:"Ahmed Al-trabulsi",           url:"https://qurango.net/radio/ahmed_altrabulsi",                 cat:"قراء",cat_en:"Readers"},
  {id:"11", name:"أحمد بن علي العجمي",name_en:"Ahmad Al-Ajmy",               url:"https://qurango.net/radio/ahmad_alajmy",                     cat:"قراء",cat_en:"Readers"},
  {id:"12", name:"أحمد خليل شاهين",  name_en:"Ahmad Shaheen",               url:"https://qurango.net/radio/ahmad_shaheen",                    cat:"قراء",cat_en:"Readers"},
  {id:"13", name:"أحمد ديبان",        name_en:"Ahmad Deban",                 url:"https://qurango.net/radio/ahmad_deban",                      cat:"قراء",cat_en:"Readers"},
  {id:"14", name:"أحمد صابر",         name_en:"Ahmad Saber",                 url:"https://qurango.net/radio/ahmad_saber",                      cat:"قراء",cat_en:"Readers"},
  {id:"15", name:"أحمد عامر",         name_en:"Ahmed Amer",                  url:"https://qurango.net/radio/ahmed_amer",                       cat:"قراء",cat_en:"Readers"},
  {id:"16", name:"أحمد نعينع",        name_en:"Ahmad Nauina",                url:"https://qurango.net/radio/ahmad_nauina",                     cat:"قراء",cat_en:"Readers"},
  {id:"19", name:"أكرم العلاقمي",     name_en:"Akram Alalaqmi",              url:"https://qurango.net/radio/akram_alalaqmi",                   cat:"قراء",cat_en:"Readers"},
  {id:"20", name:"إبراهيم الأخضر",    name_en:"Ibrahim Al-Akdar",            url:"https://qurango.net/radio/ibrahim_alakdar",                  cat:"قراء",cat_en:"Readers"},
  {id:"21", name:"إدريس أبكر",        name_en:"Idrees Abkr",                 url:"https://qurango.net/radio/idrees_abkr",                      cat:"قراء",cat_en:"Readers"},
  {id:"25", name:"الزين محمد أحمد",   name_en:"Alzain Mohammad Ahmad",       url:"https://qurango.net/radio/alzain_mohammad_ahmad",            cat:"قراء",cat_en:"Readers"},
  {id:"32", name:"بندر بليله",         name_en:"Bandar Balilah",              url:"https://qurango.net/radio/bandar_balilah",                   cat:"قراء",cat_en:"Readers"},
  {id:"53", name:"توفيق الصايغ",       name_en:"Tawfeeq As-Sayegh",          url:"https://qurango.net/radio/tawfeeq_assayegh",                 cat:"قراء",cat_en:"Readers"},
  {id:"54", name:"جمال شاكر عبدالله", name_en:"Jamal Shaker Abdullah",      url:"https://qurango.net/radio/jamal_shaker_abdullah",            cat:"قراء",cat_en:"Readers"},
  {id:"55", name:"جمعان العصيمي",      name_en:"Jamaan Alosaimi",             url:"https://qurango.net/radio/jamaan_alosaimi",                  cat:"قراء",cat_en:"Readers"},
  {id:"56", name:"حاتم فريد الواعر",  name_en:"Hatem Farid",                 url:"https://qurango.net/radio/abdullah_alkandari",               cat:"قراء",cat_en:"Readers"},
  {id:"57", name:"خالد الجليل",        name_en:"Khalid Al-Jileel",            url:"https://qurango.net/radio/khalid_aljileel",                  cat:"قراء",cat_en:"Readers"},
  {id:"58", name:"خالد القحطاني",      name_en:"Khaled Al-Qahtani",           url:"https://qurango.net/radio/khaled_alqahtani",                 cat:"قراء",cat_en:"Readers"},
  {id:"59", name:"خالد المهنا",         name_en:"Khalid Almohana",             url:"https://qurango.net/radio/khalid_almohana",                  cat:"قراء",cat_en:"Readers"},
  {id:"60", name:"خالد عبدالكافي",     name_en:"Khalid Abdulkafi",            url:"https://qurango.net/radio/khalid_abdulkafi",                 cat:"قراء",cat_en:"Readers"},
  {id:"61", name:"خليفة الطنيجي",      name_en:"Khalifa Altunaiji",           url:"https://qurango.net/radio/khalifa_altunaiji",                cat:"قراء",cat_en:"Readers"},
  {id:"62", name:"زكي داغستاني",       name_en:"Zaki Daghistani",             url:"https://qurango.net/radio/zaki_daghistani",                  cat:"قراء",cat_en:"Readers"},
  {id:"63", name:"سعد الغامدي",        name_en:"Saad Al-Ghamdi",              url:"https://qurango.net/radio/saad_alghamdi",                    cat:"قراء",cat_en:"Readers"},
  {id:"64", name:"سعود الشريم",        name_en:"Saud Al-Shuraim",             url:"https://qurango.net/radio/saud_alshuraim",                   cat:"قراء",cat_en:"Readers"},
  {id:"65", name:"سهل ياسين",          name_en:"Sahl Yassin",                 url:"https://qurango.net/radio/sahl_yassin",                      cat:"قراء",cat_en:"Readers"},
  {id:"66", name:"سيد رمضان",          name_en:"Sayeed Ramadan",              url:"https://qurango.net/radio/sayeed_ramadan",                   cat:"قراء",cat_en:"Readers"},
  {id:"67", name:"أبو بكر الشاطري",    name_en:"Abu Bakr Al Shatri",          url:"https://qurango.net/radio/shaik_abu_bakr_al_shatri",         cat:"قراء",cat_en:"Readers"},
  {id:"68", name:"شيرزاد طاهر",        name_en:"Shirazad Taher",              url:"https://qurango.net/radio/shirazad_taher",                   cat:"قراء",cat_en:"Readers"},
  {id:"69", name:"صابر عبدالحكب",      name_en:"Saber Abdulhakm",             url:"https://qurango.net/radio/saber_abdulhakm",                  cat:"قراء",cat_en:"Readers"},
  {id:"70", name:"صلاح البدير",         name_en:"Salah Albudair",              url:"https://qurango.net/radio/salah_albudair",                   cat:"قراء",cat_en:"Readers"},
  {id:"71", name:"صلاح الهاشم",         name_en:"Salah Alhashim",              url:"https://qurango.net/radio/salah_alhashim",                   cat:"قراء",cat_en:"Readers"},
  {id:"72", name:"صلاح بو خاطر",       name_en:"Slaah Bukhatir",              url:"https://qurango.net/radio/slaah_bukhatir",                   cat:"قراء",cat_en:"Readers"},
  {id:"74", name:"عادل الكلباني",       name_en:"Adel Al-Khalbany",            url:"https://qurango.net/radio/adel_alkhalbany",                  cat:"قراء",cat_en:"Readers"},
  {id:"75", name:"عادل ريان",           name_en:"Adel Ryyan",                  url:"https://qurango.net/radio/adel_ryyan",                       cat:"قراء",cat_en:"Readers"},
  {id:"76", name:"عبدالبارئ الثبيتي",  name_en:"Abdelbari Al-Toubayti",       url:"https://qurango.net/radio/abdelbari_altoubayti",             cat:"قراء",cat_en:"Readers"},
  {id:"77", name:"عبدالبارئ محمد",      name_en:"Abdulbari Mohammad",          url:"https://qurango.net/radio/abdulbari_mohammad",               cat:"قراء",cat_en:"Readers"},
  {id:"78", name:"عبدالباسط عبدالصمد", name_en:"Abdulbasit Abdulsamad",       url:"https://qurango.net/radio/abdulbasit_abdulsamad",            cat:"قراء",cat_en:"Readers"},
  {id:"79", name:"عبدالباسط - مجود",   name_en:"Abdulbasit (Mojawwad)",       url:"https://qurango.net/radio/abdulbasit_abdulsamad_mojawwad",   cat:"قراء",cat_en:"Readers"},
  {id:"81", name:"عبدالرحمن السديس",   name_en:"Abdulrahman Alsudaes",        url:"https://qurango.net/radio/abdulrahman_alsudaes",             cat:"قراء",cat_en:"Readers"},
  {id:"82", name:"عبدالرحمن الماجد",   name_en:"Abdulrahman Al-Majed",        url:"https://qurango.net/radio/abdulrahman_almajed",              cat:"قراء",cat_en:"Readers"},
  {id:"85", name:"عبدالعزيز الأحمد",   name_en:"Abdul Aziz Al-Ahmad",         url:"https://qurango.net/radio/abdul_aziz_alahmad",               cat:"قراء",cat_en:"Readers"},
  {id:"86", name:"عبدالله الخلف",      name_en:"Abdullah Al-Khalaf",          url:"https://qurango.net/radio/abdullah_alkhalaf",                cat:"قراء",cat_en:"Readers"},
  {id:"87", name:"عبدالله الكندري",     name_en:"Abdullah Al-Kandari",         url:"https://qurango.net/radio/abdullah_alkandari",               cat:"قراء",cat_en:"Readers"},
  {id:"88", name:"عبدالله المطرود",     name_en:"Abdullah Al-Mattrod",         url:"https://qurango.net/radio/abdullah_almattrod",               cat:"قراء",cat_en:"Readers"},
  {id:"89", name:"عبدالله الموسى",      name_en:"Abdullah Al-Mousa",           url:"https://qurango.net/radio/abdullah_almousa",                 cat:"قراء",cat_en:"Readers"},
  {id:"90", name:"عبدالله بصفر",        name_en:"Abdullah Basfer",             url:"https://qurango.net/radio/abdullah_basfer",                  cat:"قراء",cat_en:"Readers"},
  {id:"91", name:"عبدالله خياط",        name_en:"Abdullah Khayyat",            url:"https://qurango.net/radio/abdullah_khayyat",                 cat:"قراء",cat_en:"Readers"},
  {id:"92", name:"عبدالله عواد الجهني",name_en:"Abdullah Al-Johany",          url:"https://qurango.net/radio/abdullah_aljohany",                cat:"قراء",cat_en:"Readers"},
  {id:"93", name:"عبدالمحسن الحارثي",  name_en:"Abdulmohsin Al-Harthy",       url:"https://qurango.net/radio/abdulmohsin_alharthy",             cat:"قراء",cat_en:"Readers"},
  {id:"94", name:"عبدالمحسن العبيكان", name_en:"Abdulmohsin Al-Obaikan",      url:"https://qurango.net/radio/abdulmohsin_alobaikan",            cat:"قراء",cat_en:"Readers"},
  {id:"95", name:"عبدالمحسن القاسم",   name_en:"Abdulmohsen Al-Qasim",        url:"https://qurango.net/radio/abdulmohsen_alqasim",              cat:"قراء",cat_en:"Readers"},
  {id:"96", name:"عبدالهادي كناكري",   name_en:"Abdulhadi Kanakeri",          url:"https://qurango.net/radio/abdulhadi_kanakeri",               cat:"قراء",cat_en:"Readers"},
  {id:"97", name:"عبدالودود حنيف",      name_en:"Abdulwadood Haneef",          url:"https://qurango.net/radio/abdulwadood_haneef",               cat:"قراء",cat_en:"Readers"},
  {id:"98", name:"علي الحذيفي",         name_en:"Ali Alhuthaifi",              url:"https://qurango.net/radio/ali_alhuthaifi",                   cat:"قراء",cat_en:"Readers"},
  {id:"99", name:"علي جابر",            name_en:"Ali Jaber",                   url:"https://qurango.net/radio/ali_jaber",                        cat:"قراء",cat_en:"Readers"},
  {id:"100",name:"علي حجاج السويسي",   name_en:"Ali Hajjaj Alsouasi",         url:"https://qurango.net/radio/ali_hajjaj_alsouasi",              cat:"قراء",cat_en:"Readers"},
  {id:"101",name:"عماد زهير حافظ",      name_en:"Emad Hafez",                  url:"https://qurango.net/radio/emad_hafez",                       cat:"قراء",cat_en:"Readers"},
  {id:"103",name:"فارس عباد",           name_en:"Fares Abbad",                 url:"https://qurango.net/radio/fares_abbad",                      cat:"قراء",cat_en:"Readers"},
  {id:"106",name:"ماجد الزامل",         name_en:"Majed Al-Zamil",              url:"https://qurango.net/radio/majed_alzamel",                    cat:"قراء",cat_en:"Readers"},
  {id:"107",name:"ماهر المعيقلي",       name_en:"Maher Al Meaqli",             url:"https://qurango.net/radio/maher_al_meaqli",                  cat:"قراء",cat_en:"Readers"},
  {id:"108",name:"ماهر شخاشيرو",        name_en:"Maher Shakhashero",           url:"https://qurango.net/radio/maher_shakhashero",                cat:"قراء",cat_en:"Readers"},
  {id:"109",name:"محمد أيوب 1",         name_en:"Mohammed Ayyub 1",            url:"https://qurango.net/radio/mohammed_ayyub",                   cat:"قراء",cat_en:"Readers"},
  {id:"110",name:"محمد أيوب 2",         name_en:"Mohammed Ayyub 2",            url:"https://qurango.net/radio/ayyoub2",                          cat:"قراء",cat_en:"Readers"},
  {id:"111",name:"محمد الطبلاوي",       name_en:"Mohammad Al-Tablaway",        url:"https://qurango.net/radio/mohammad_altablaway",              cat:"قراء",cat_en:"Readers"},
  {id:"112",name:"محمد اللحيدان",       name_en:"Mohammed Al-Lohaidan",        url:"https://qurango.net/radio/mohammed_allohaidan",              cat:"قراء",cat_en:"Readers"},
  {id:"113",name:"محمد جبريل",          name_en:"Mohammed Jibreel",            url:"https://qurango.net/radio/mohammed_jibreel",                 cat:"قراء",cat_en:"Readers"},
  {id:"114",name:"محمد رشاد الشريف",   name_en:"Mohammad Rashad Alshareef",   url:"https://qurango.net/radio/mohammad_rashad_alshareef",        cat:"قراء",cat_en:"Readers"},
  {id:"115",name:"محمد صالح عالم شاه", name_en:"Mohammad Saleh Alim Shah",    url:"https://qurango.net/radio/mohammad_saleh_alim_shah",         cat:"قراء",cat_en:"Readers"},
  {id:"116",name:"محمد صديق المنشاوي", name_en:"Mohammed Siddiq Al-Minshawi", url:"https://qurango.net/radio/mohammed_siddiq_alminshawi",       cat:"قراء",cat_en:"Readers"},
  {id:"117",name:"المنشاوي - مجود",    name_en:"Al-Minshawi (Mojawwad)",      url:"https://qurango.net/radio/mohammed_siddiq_alminshawi_mojawwad",cat:"قراء",cat_en:"Readers"},
  {id:"120",name:"محمد عبدالكريم",      name_en:"Mohammad Abdullkarem",        url:"https://qurango.net/radio/mohammad_abdullkarem",             cat:"قراء",cat_en:"Readers"},
  {id:"122",name:"محمد عثمان خان",      name_en:"Mohammed Osman Khan",         url:"https://qurango.net/radio/mohammed_osman_khan",              cat:"قراء",cat_en:"Readers"},
  {id:"123",name:"محمود الرفاعي",       name_en:"Mahmood Al rifai",            url:"https://qurango.net/radio/mahmood_al_rifai",                 cat:"قراء",cat_en:"Readers"},
  {id:"125",name:"محمود خليل الحصري",  name_en:"Mahmoud Khalil Al-Hussary",   url:"https://qurango.net/radio/mahmoud_khalil_alhussary",         cat:"قراء",cat_en:"Readers"},
  {id:"126",name:"الحصري - مجود",       name_en:"AlHussary (Mojawwad)",        url:"https://qurango.net/radio/mahmoud_khalil_alhussary_mojawwad", cat:"قراء",cat_en:"Readers"},
  {id:"128",name:"محمود علي البنا",     name_en:"Mahmoud Ali Albanna",         url:"https://qurango.net/radio/mahmoud_ali__albanna",             cat:"قراء",cat_en:"Readers"},
  {id:"129",name:"البنا - مجود",        name_en:"Mahmoud Ali Albanna (Mojawwad)",url:"https://qurango.net/radio/mahmoud_ali__albanna_mojawwad", cat:"قراء",cat_en:"Readers"},
  {id:"130",name:"مشاري العفاسي",       name_en:"Mishary Alafasi",             url:"https://qurango.net/radio/mishary_alafasi",                  cat:"قراء",cat_en:"Readers"},
  {id:"131",name:"مصطفى إسماعيل",       name_en:"Mustafa Ismail",              url:"https://qurango.net/radio/mustafa_ismail",                   cat:"قراء",cat_en:"Readers"},
  {id:"132",name:"مصطفى اللاهوني",      name_en:"Mustafa Al-Lahoni",           url:"https://qurango.net/radio/mustafa_allahoni",                 cat:"قراء",cat_en:"Readers"},
  {id:"133",name:"مصطفى رعد العزاوي",  name_en:"Mustafa raad Alazawy",        url:"https://qurango.net/radio/mustafa_raad_alazawy",             cat:"قراء",cat_en:"Readers"},
  {id:"134",name:"معيض الحارثي",        name_en:"Moeedh Alharthi",             url:"https://qurango.net/radio/moeedh_alharthi",                  cat:"قراء",cat_en:"Readers"},
  {id:"135",name:"مفتاح السلطني",        name_en:"Muftah Alsaltany",            url:"https://qurango.net/radio/muftah_alsaltany",                 cat:"قراء",cat_en:"Readers"},
  {id:"139",name:"موسى بلال",            name_en:"Mousa Bilal",                 url:"https://qurango.net/radio/mousa_bilal",                      cat:"قراء",cat_en:"Readers"},
  {id:"140",name:"ناصر العصفور",         name_en:"Nasser Alosfor",              url:"https://qurango.net/radio/nasser_alosfor",                   cat:"قراء",cat_en:"Readers"},
  {id:"141",name:"ناصر القطامي",         name_en:"Nasser Alqatami",             url:"https://qurango.net/radio/nasser_alqatami",                  cat:"قراء",cat_en:"Readers"},
  {id:"142",name:"ناصر الماجد",          name_en:"Nasser Almajed",              url:"https://qurango.net/radio/nasser_almajed",                   cat:"قراء",cat_en:"Readers"},
  {id:"143",name:"نبيل الرفاعي",         name_en:"Nabil Al Rifay",              url:"https://qurango.net/radio/nabil_al_rifay",                   cat:"قراء",cat_en:"Readers"},
  {id:"144",name:"نعمة الحسان",          name_en:"Neamah Al-Hassan",            url:"https://qurango.net/radio/neamah_alhassan",                  cat:"قراء",cat_en:"Readers"},
  {id:"145",name:"هاني الرفاعي",         name_en:"Hani Arrifai",                url:"https://qurango.net/radio/hani_arrifai",                     cat:"قراء",cat_en:"Readers"},
  {id:"146",name:"هيثم الجدعاني",        name_en:"Hitham Aljadani",             url:"https://qurango.net/radio/hitham_aljadani",                  cat:"قراء",cat_en:"Readers"},
  {id:"148",name:"ياسر الدوسري",         name_en:"Yasser Al-Dosari",            url:"https://qurango.net/radio/yasser_aldosari",                  cat:"قراء",cat_en:"Readers"},
  {id:"149",name:"ياسر القرشي",          name_en:"Yasser Al-Qurashi",           url:"https://qurango.net/radio/yasser_alqurashi",                 cat:"قراء",cat_en:"Readers"},
  {id:"151",name:"يحيى حوا",             name_en:"Yahya Hawwa",                 url:"https://qurango.net/radio/yahya_hawwa",                      cat:"قراء",cat_en:"Readers"},
  {id:"152",name:"يوسف الشويعي",         name_en:"Yousef Alshoaey",             url:"https://qurango.net/radio/yousef_alshoaey",                  cat:"قراء",cat_en:"Readers"},
  {id:"153",name:"يوسف بن نوح أحمد",    name_en:"Yousef Bin Noah Ahmad",       url:"https://qurango.net/radio/yousef_bin_noah_ahmad",            cat:"قراء",cat_en:"Readers"},

  {id:"10", name:"أحمد الطرالسي - قالون",         name_en:"Ahmad Khader (Qalon)",          url:"https://qurango.net/radio/ahmad_khader_altarabulsi",         cat:"روايات",cat_en:"Rewayat"},
  {id:"22", name:"ابراهيم الدوسري - ورش",         name_en:"Ibrahim Aldosari (Warsh)",      url:"https://qurango.net/radio/ibrahim_aldosari",                  cat:"روايات",cat_en:"Rewayat"},
  {id:"23", name:"الدوكالي محمد العالم - قالون",  name_en:"Addokali Mohammad (Qalon)",     url:"https://qurango.net/radio/addokali_mohammad_alalim",          cat:"روايات",cat_en:"Rewayat"},
  {id:"26", name:"العيون الكوشي - ورش",            name_en:"Aloyoon Al-Koshi (Warsh)",      url:"https://qurango.net/radio/aloyoon_alkoshi",                   cat:"روايات",cat_en:"Rewayat"},
  {id:"27", name:"الفاتح محمد الزبير - الدوري",   name_en:"Alfateh Alzubair (Aldori)",     url:"https://qurango.net/radio/alfateh_alzubair",                  cat:"روايات",cat_en:"Rewayat"},
  {id:"29", name:"القارئ ياسين - ورش",             name_en:"Al-Qaria Yassen (Warsh)",       url:"https://qurango.net/radio/alqaria_yassen",                    cat:"روايات",cat_en:"Rewayat"},
  {id:"73", name:"طارق دعوب - قالون",              name_en:"Tareq Daawob (Qalon)",          url:"https://qurango.net/radio/tareq_abdulgani_daawob",            cat:"روايات",cat_en:"Rewayat"},
  {id:"80", name:"عبدالباسط - ورش",                name_en:"Abdulbasit (Warsh)",            url:"https://qurango.net/radio/abdulbasit_abdulsamad_warsh",       cat:"روايات",cat_en:"Rewayat"},
  {id:"83", name:"عبدالرشيد صوفي - السوسي",       name_en:"Abdulrasheed Soufi (Sosi)",     url:"https://qurango.net/radio/abdulrasheed_soufi_assosi",         cat:"روايات",cat_en:"Rewayat"},
  {id:"84", name:"عبدالرشيد صوفي - خلف",          name_en:"Abdulrasheed Soufi (Khalaf)",   url:"https://qurango.net/radio/abdulrasheed_soufi_khalaf",         cat:"روايات",cat_en:"Rewayat"},
  {id:"102",name:"عمر القزابري - ورش",             name_en:"Omar Al-Qazabri (Warsh)",       url:"https://qurango.net/radio/omar_alqazabri",                    cat:"روايات",cat_en:"Rewayat"},
  {id:"118",name:"محمد عبدالحكيم - البزي",         name_en:"Mohammad Al-Abdullah (Albizi)", url:"https://qurango.net/radio/mohammad_alabdullah_albizi",        cat:"روايات",cat_en:"Rewayat"},
  {id:"119",name:"محمد عبدالحكيم - الدوري",        name_en:"Mohammad Al-Abdullah (Aldorai)",url:"https://qurango.net/radio/mohammad_alabdullah_aldorai",       cat:"روايات",cat_en:"Rewayat"},
  {id:"121",name:"محمد عبدالكريم - ورش",           name_en:"Mohammad Abdullkarem (Warsh)",  url:"https://qurango.net/radio/mohammad_abdullkarem_alasbahani",  cat:"روايات",cat_en:"Rewayat"},
  {id:"124",name:"محمود الشيمي - الدوري",          name_en:"Mahmood AlSheimy (Aldorai)",    url:"https://qurango.net/radio/mahmood_alsheimy",                  cat:"روايات",cat_en:"Rewayat"},
  {id:"127",name:"محمود خليل الحصري - ورش",       name_en:"AlHussary (Warsh)",             url:"https://qurango.net/radio/mahmoud_khalil_alhussary_warsh",    cat:"روايات",cat_en:"Rewayat"},
  {id:"136",name:"مفتاح السلطني - ابن ذكوان",     name_en:"Muftah Alsaltany (Ibn Thakwan)",url:"https://qurango.net/radio/muftah_alsaltany_ibn_thakwan_an_ibn_amr",cat:"روايات",cat_en:"Rewayat"},
  {id:"137",name:"مفتاح السلطني - الدوري",         name_en:"Muftah Alsaltany (Aldori)",     url:"https://qurango.net/radio/muftah_alsaltany_aldori_an_abi_amr",cat:"روايات",cat_en:"Rewayat"},
  {id:"138",name:"مفتاح السلطني - الدوري الكسائي",name_en:"Muftah Alsaltany (Aldorai)",    url:"https://qurango.net/radio/muftah_alsaltany_aldorai",           cat:"روايات",cat_en:"Rewayat"},
  {id:"147",name:"وليد النائحي - قالون",            name_en:"Waleed Alnaehi (Qalon)",        url:"https://qurango.net/radio/waleed_alnaehi",                    cat:"روايات",cat_en:"Rewayat"},
  {id:"150",name:"ياسر المزروعي - رويس وروح",      name_en:"Yasser Al-Mazroyee (Rowis)",    url:"https://qurango.net/radio/yasser_almazroyee",                 cat:"روايات",cat_en:"Rewayat"},

  {id:"33", name:"ترجمة الأردية - عبدالباسط",    name_en:"Urdu Translation (Basit)",     url:"https://qurango.net/radio/translation_quran_urdu_basit",             cat:"ترجمة",cat_en:"Translation"},
  {id:"34", name:"ترجمة الأسبانية",               name_en:"Spanish Translation",          url:"https://qurango.net/radio/translation_quran_spanish_afs",            cat:"ترجمة",cat_en:"Translation"},
  {id:"35", name:"ترجمة الألبانية",                name_en:"Albanian Translation",         url:"https://qurango.net/radio/translation_quran_albanian",               cat:"ترجمة",cat_en:"Translation"},
  {id:"36", name:"ترجمة الألمانية",                name_en:"German Translation",           url:"https://qurango.net/radio/translation_quran_german",                 cat:"ترجمة",cat_en:"Translation"},
  {id:"37", name:"ترجمة الأمازيغية",              name_en:"Tamazight Translation",        url:"https://qurango.net/radio/translation_quran_tamazight",              cat:"ترجمة",cat_en:"Translation"},
  {id:"38", name:"ترجمة الأردية - السديس",        name_en:"Urdu Translation (Sudais)",    url:"https://qurango.net/radio/translation_quran_urdu_sds_shur",          cat:"ترجمة",cat_en:"Translation"},
  {id:"39", name:"ترجمة الأردية - المنشاوي",      name_en:"Urdu Translation (Minshawi)",  url:"https://qurango.net/radio/translation_quran_urdu_minsh",             cat:"ترجمة",cat_en:"Translation"},
  {id:"40", name:"ترجمة الإنجليزية - عبدالباسط", name_en:"English Translation (Basit)",  url:"https://qurango.net/radio/translation_quran_english_basit",          cat:"ترجمة",cat_en:"Translation"},
  {id:"41", name:"ترجمة الإنجليزية - بصفر",       name_en:"English Translation (Basfr)",  url:"https://qurango.net/radio/translation_quran_english_bsfr",           cat:"ترجمة",cat_en:"Translation"},
  {id:"42", name:"ترجمة الإنجليزية - Walk",       name_en:"English Translation (Walk)",   url:"https://qurango.net/radio/translation_quran_english_walk_basit",     cat:"ترجمة",cat_en:"Translation"},
  {id:"43", name:"ترجمة البرتغالية",              name_en:"Portuguese Translation",       url:"https://qurango.net/radio/translation_quran_portuguese",             cat:"ترجمة",cat_en:"Translation"},
  {id:"44", name:"ترجمة البوسنية",                name_en:"Bosnian Translation",          url:"https://qurango.net/radio/translation_quran_bosnia",                 cat:"ترجمة",cat_en:"Translation"},
  {id:"45", name:"ترجمة التركية",                 name_en:"Turkish Translation",          url:"https://qurango.net/radio/translation_quran_turkish",                cat:"ترجمة",cat_en:"Translation"},
  {id:"46", name:"ترجمة الصينية",                 name_en:"Chinese Translation",          url:"https://qurango.net/radio/translation_quran_chinese",                cat:"ترجمة",cat_en:"Translation"},
  {id:"47", name:"ترجمة الفارسية",                name_en:"Farsi Translation",            url:"https://qurango.net/radio/translation_quran_farsi",                  cat:"ترجمة",cat_en:"Translation"},
  {id:"48", name:"ترجمة الفرنسية",                name_en:"French Translation",           url:"https://qurango.net/radio/translation_quran_french",                 cat:"ترجمة",cat_en:"Translation"},
  {id:"49", name:"ترجمة الكردية",                 name_en:"Kurdish Translation",          url:"https://qurango.net/radio/translation_quran_kurdish",                cat:"ترجمة",cat_en:"Translation"},
  {id:"50", name:"ترجمة المجرية",                 name_en:"Hungarian Translation",        url:"https://qurango.net/radio/translation_quran_hungarian",              cat:"ترجمة",cat_en:"Translation"},
  {id:"51", name:"ترجمة اليونانية",               name_en:"Greek Translation",            url:"https://qurango.net/radio/translation_quran_greek",                  cat:"ترجمة",cat_en:"Translation"},

  {id:"yt1",name:"قناة القرآن الكريم",  name_en:"Quran Channel Live",  url:"https://win.holol.com/live/quran/playlist.m3u8",  video:true, yt:"https://www.youtube.com/channel/UCos52azQNBgW63_9uDJoPDA/live",cat:"بث مباشر",cat_en:"Live"},
  {id:"yt2",name:"قناة السنة النبوية",   name_en:"Sunnah Channel Live", url:"https://win.holol.com/live/sunnah/playlist.m3u8", video:true, yt:"https://www.youtube.com/channel/UCROKYPep-UuODNwyipe6JMw/live",cat:"بث مباشر",cat_en:"Live"}
];
